{{- $name := "disableAutomountServiceAccountToken" }}
{{- $category := "other" }}
{{- $policyValues := get .Values.policies $name }}
{{- $categoryValues := get .Values.policyCategories $category }}

{{- if include "kyverno-policies.enabled" (list $name $category $) }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ kebabcase $name }}
  annotations:
{{- with $policyValues.autogenControllers }}
    pod-policies.kyverno.io/autogen-controllers: {{ . }}
{{- end }}
    policies.kyverno.io/title: Disable automountServiceAccountToken
    policies.kyverno.io/category: {{ $category }}, EKS Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: ServiceAccount
    kyverno.io/kyverno-version: 1.6.0
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.21"
    policies.kyverno.io/description: >-
      A new ServiceAccount called `default` is created whenever a new Namespace is created.
      Pods spawned in that Namespace, unless otherwise set, will be assigned this ServiceAccount.
      This policy mutates any new `default` ServiceAccounts to disable auto-mounting of the token
      into Pods obviating the need to do so individually.
spec:
{{ include "kyverno-policies.policySettings" (list $name $category $) }}
#{{- if $policyValues.mutateDefaultServiceAccount }}
#  mutateExistingOnPolicyUpdate: true #Mutates already existing matching resources
#{{- end }}
  rules:
{{- if $policyValues.rulesOverride }}
{{ toYaml $policyValues.rulesOverride | indent 4 }}
{{- else }}
    - name: check-automountserviceaccounttoken
      match:
        any:
          - resources:
              kinds:
                - ServiceAccount
              names:
                - default
{{- if $policyValues.exclude }}
      exclude: {{ toYaml $policyValues.exclude | nindent 8 }}
{{- end }}
      validate:
        message: 'automountServiceAccountToken should be set to false for default service account'
        pattern:
          automountServiceAccountToken: false
#{{- if $policyValues.mutateDefaultServiceAccount }}
#    - name: disable-automountserviceaccounttoken
#      match:
#        any:
#          - resources:
#              kinds:
#                - ServiceAccount
#              names:
#                - default
#{{- if $policyValues.exclude }}
#      exclude: {{ toYaml $policyValues.exclude | nindent 8 }}
#{{- end }}
#      mutate:
#        targets: # Allows modification of existing resources, permissions for serviceaccounts must be added to Kyverno generatecontrollerExtraResources
#          - apiVersion: v1
#            kind: ServiceAccount
#        patchStrategicMerge:
#          automountServiceAccountToken: false
#{{- end }}
{{- end }}
{{- end }}
