{{- $name := "disableServiceDiscovery" }}
{{- $category := "other" }}
{{- $policyValues := get .Values.policies $name }}
{{- $categoryValues := get .Values.policyCategories $category }}

{{- if include "kyverno-policies.enabled" (list $name $category $) }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ kebabcase $name }}
  annotations:
{{- with $policyValues.autogenControllers }}
    pod-policies.kyverno.io/autogen-controllers: {{ . }}
{{- end }}
    policies.kyverno.io/title: Disable Service Discovery
    policies.kyverno.io/category: {{ $category }}, EKS Best Practices
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.8.0-rc2
    kyverno.io/kubernetes-version: "1.24"
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      Not all Pods require communicating with other Pods or resolving in-cluster Services.
      For those, disabling service discovery can increase security as the Pods are limited
      to what they can see. This policy checks which Pods set dnsPolicy to `Default` and
      enableServiceLinks to `false`, i.e. have service discovery disabled.
spec:
{{ include "kyverno-policies.policySettings" (list $name $category $) }}
  rules:
{{- if $policyValues.rulesOverride }}
{{ toYaml $policyValues.rulesOverride | indent 4 }}
{{- else }}
    - name: check-dnspolicy-default
      match:
        any:
          - resources:
              kinds:
                - Pod
{{- if $policyValues.exclude }}
      exclude: {{ toYaml $policyValues.exclude | nindent 8 }}
{{- end }}
      validate:
        message: 'dnsPolicy should be set to Default and enableServiceLinks should be set to false'
        pattern:
          spec:
            dnsPolicy: Default
            enableServiceLinks: false
{{- end }}
{{- end }}
