{{- $name := "restrictServiceExternalIps" }}
{{- $category := "other" }}
{{- $policyValues := get .Values.policies $name }}
{{- $categoryValues := get .Values.policyCategories $category }}

{{- if include "kyverno-policies.enabled" (list $name $category $) }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ kebabcase $name }}
  annotations:
{{- with $policyValues.autogenControllers }}
    pod-policies.kyverno.io/autogen-controllers: {{ . }}
{{- end }}
    policies.kyverno.io/title: Restrict External IPs
    policies.kyverno.io/category: {{ $category }}, Best Practices
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Service
    policies.kyverno.io/description: >-
      Service externalIPs can be used for a MITM attack (CVE-2020-8554).
      Restrict externalIPs or limit to a known set of addresses.
      See: https://github.com/kyverno/kyverno/issues/1367. This policy validates
      that the `externalIPs` field is not set on a Service.
spec:
{{ include "kyverno-policies.policySettings" (list $name $category $) }}
  rules:
{{- if $policyValues.rulesOverride }}
{{ toYaml $policyValues.rulesOverride | indent 4 }}
{{- else }}
    - name: check-ips
      match:
        any:
          - resources:
              kinds:
                - Service
{{- if $policyValues.exclude }}
      exclude: {{ toYaml $policyValues.exclude | nindent 8 }}
{{- end }}
      validate:
        message: "externalIPs are not allowed."
        pattern:
          spec:
            # restrict external IP addresses
            # you can alternatively restrict to a known set of addresses using:
            #     =(externalIPs): ["37.10.11.53", "153.10.20.1"]
            X(externalIPs): "null"
{{- end }}
{{- end }}
